modLoader="javafml"
loaderVersion="[32,)"

[[mods]]

modId="yellowstone"
version="0.1.0"
displayName="Yellowstone"
logoFile="yellowstone.png"
authors="Ian Rehwinkel, Sebastian Gerdon & Robin Gerdon"
description='''
This mod adds the mysterious yellowstone world...
'''
[[dependencies.yellowstone]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.yellowstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
